### ISSUE TITLE
Does it work if the Moodle is not in the webserver root?

### ISSUE THREAD

**Issue by mudrd8mz** [blackbean/moodle-mod_vimeo#3]
Code like
```
    if ($styles == true) {
        $output .= '<link href="/mod/vimeo/style.css" rel="stylesheet" media="all"/>'."\n";
    }
```
looks like it will not work if the Moodle is not installed in the root of the domain right?

**Comment by brunomagalhaes** [comment]
Hi David,

Thank you for your help, really appreciate it.

Yes, unfortunately that assumption was true. But we just fixed it within our last commit.

Best,
Bruno
